services:
  db:
    image: postgres:15
    container_name: postgres-academia
    environment:
      POSTGRES_USER: reginaldo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: academia_db
    ports:
      - "5432:5432"